# https://taskfile.dev
version: '3'

vars:
  BRANCH_PREFIX_RELEASE: release/
  BRANCH_PREFIX_PROJECT: project/
  BRANCH_PREFIX_ISSUE: issue/
  BRANCH_PRODUCTION: distributed

includes:
  branch: ./.tasks/{{OS}}/branching.yml
  tag: ./.tasks/{{OS}}/tags.yml
  val: ./.tasks/{{OS}}/validate.yml
  

tasks:
  setup: 
    desc: Setup the project for development
    deps: 
      - task: val:confirmGit
      - task: val:confirmCurl
    cmds:
      - task: val:dlFile
        vars: {IN: "https://raw.githubusercontent.com/krakentech/kt_project_tools/1.0.0/githooks/prepare-commit-msg", OUT: "./.git/hooks/prepare-commit-msg", ERR: "Unable to download the commit hook file"}
      - cmd: chmod +x "./.git/hooks/prepare-commit-msg"
      - cmd: echo "Setup Compelete"
    silent: true

  validate:
    desc: verify that all the needed tools for tasks are available
    cmds: 
      - echo "Validate"

  default:
    cmds:
      - task -l
    silent: true
